[tool.poetry]
name = "vscode-mypy-repro"
version = "0.1.0"
description = ""
authors = ["jrheard"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
mypy = "^1.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
